name: pages build and deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
          name: github-pages
          retention-days: 1

  report-build-status:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Report build status
        run: echo "Build status reported"

  deploy:
    runs-on: ubuntu-latest
    needs: report-build-status

    permissions:
      pages: write
      id-token: write 

    steps:          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: github-pages